/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/a/{version_id}/{file_path}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Serve Asset */
    get: operations["serve_asset_a__version_id___file_path__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/audit": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Audit */
    get: operations["list_audit_api_v1_admin_audit_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/deck-prompt-jobs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Deck Prompt Jobs Admin */
    get: operations["list_deck_prompt_jobs_admin_api_v1_admin_deck_prompt_jobs_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/jobs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Export Jobs Admin */
    get: operations["list_export_jobs_admin_api_v1_admin_jobs_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/logs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Logs */
    get: operations["list_logs_api_v1_admin_logs_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/presentations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Presentations Admin */
    get: operations["list_presentations_admin_api_v1_admin_presentations_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/settings/entra": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Admin Entra Settings Get */
    get: operations["admin_entra_settings_get_api_v1_admin_settings_entra_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Admin Entra Settings Patch */
    patch: operations["admin_entra_settings_patch_api_v1_admin_settings_entra_patch"];
    trace?: never;
  };
  "/api/v1/admin/settings/llm": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Admin Llm Settings Get */
    get: operations["admin_llm_settings_get_api_v1_admin_settings_llm_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Admin Llm Settings Patch */
    patch: operations["admin_llm_settings_patch_api_v1_admin_settings_llm_patch"];
    trace?: never;
  };
  "/api/v1/admin/settings/smtp": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Admin Smtp Settings Get */
    get: operations["admin_smtp_settings_get_api_v1_admin_settings_smtp_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Admin Smtp Settings Patch */
    patch: operations["admin_smtp_settings_patch_api_v1_admin_settings_smtp_patch"];
    trace?: never;
  };
  "/api/v1/admin/settings/smtp/test": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Admin Smtp Test */
    post: operations["admin_smtp_test_api_v1_admin_settings_smtp_test_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/setup": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Admin Setup */
    get: operations["admin_setup_api_v1_admin_setup_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/stats": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Admin Stats */
    get: operations["admin_stats_api_v1_admin_stats_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Users */
    get: operations["list_users_api_v1_admin_users_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/config": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Auth Config */
    get: operations["auth_config_api_v1_auth_config_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/entra/callback": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Entra Callback */
    get: operations["entra_callback_api_v1_auth_entra_callback_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/entra/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Entra Login */
    get: operations["entra_login_api_v1_auth_entra_login_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login */
    post: operations["login_api_v1_auth_login_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Logout */
    post: operations["logout_api_v1_auth_logout_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Me */
    get: operations["me_api_v1_auth_me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/me/settings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Me Settings */
    get: operations["me_settings_api_v1_auth_me_settings_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Me Settings Patch */
    patch: operations["me_settings_patch_api_v1_auth_me_settings_patch"];
    trace?: never;
  };
  "/api/v1/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Refresh */
    post: operations["refresh_api_v1_auth_refresh_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/comments/{comment_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete Comment */
    delete: operations["delete_comment_api_v1_comments__comment_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/deck-prompt-jobs/{job_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Deck Prompt Job */
    get: operations["get_deck_prompt_job_api_v1_deck_prompt_jobs__job_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/directory/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Directory Users */
    get: operations["directory_users_api_v1_directory_users_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/exports/{job_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Export Job */
    get: operations["get_export_job_api_v1_exports__job_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/exports/{job_id}/file": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Download Export File */
    get: operations["download_export_file_api_v1_exports__job_id__file_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/presentations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Presentations */
    get: operations["list_presentations_api_v1_presentations_get"];
    put?: never;
    /** Create Presentation */
    post: operations["create_presentation_api_v1_presentations_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/presentations/generate-from-prompt": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Generate Presentation From Prompt */
    post: operations["generate_presentation_from_prompt_api_v1_presentations_generate_from_prompt_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/presentations/{presentation_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Presentation Detail */
    get: operations["get_presentation_detail_api_v1_presentations__presentation_id__get"];
    put?: never;
    post?: never;
    /** Delete Presentation */
    delete: operations["delete_presentation_api_v1_presentations__presentation_id__delete"];
    options?: never;
    head?: never;
    /** Update Presentation */
    patch: operations["update_presentation_api_v1_presentations__presentation_id__patch"];
    trace?: never;
  };
  "/api/v1/presentations/{presentation_id}/deck-prompt-jobs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Deck Prompt Job */
    post: operations["create_deck_prompt_job_api_v1_presentations__presentation_id__deck_prompt_jobs_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/presentations/{presentation_id}/embed": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Embed Iframe */
    get: operations["embed_iframe_api_v1_presentations__presentation_id__embed_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/presentations/{presentation_id}/exports": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Export Job */
    post: operations["create_export_job_api_v1_presentations__presentation_id__exports_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/presentations/{presentation_id}/members": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Presentation Members */
    get: operations["list_presentation_members_api_v1_presentations__presentation_id__members_get"];
    put?: never;
    /** Create Presentation Member */
    post: operations["create_presentation_member_api_v1_presentations__presentation_id__members_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/presentations/{presentation_id}/members/{member_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete Presentation Member */
    delete: operations["delete_presentation_member_api_v1_presentations__presentation_id__members__member_id__delete"];
    options?: never;
    head?: never;
    /** Update Presentation Member */
    patch: operations["update_presentation_member_api_v1_presentations__presentation_id__members__member_id__patch"];
    trace?: never;
  };
  "/api/v1/presentations/{presentation_id}/share-links": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Share Links */
    get: operations["list_share_links_api_v1_presentations__presentation_id__share_links_get"];
    put?: never;
    /** Create Share Link */
    post: operations["create_share_link_api_v1_presentations__presentation_id__share_links_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/presentations/{presentation_id}/share-links/{share_link_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Revoke Share Link */
    delete: operations["revoke_share_link_api_v1_presentations__presentation_id__share_links__share_link_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/presentations/{presentation_id}/threads": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Threads */
    get: operations["list_threads_api_v1_presentations__presentation_id__threads_get"];
    put?: never;
    /** Create Thread */
    post: operations["create_thread_api_v1_presentations__presentation_id__threads_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/presentations/{presentation_id}/versions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Versions */
    get: operations["list_versions_api_v1_presentations__presentation_id__versions_get"];
    put?: never;
    /** Upload Html Version */
    post: operations["upload_html_version_api_v1_presentations__presentation_id__versions_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/presentations/{presentation_id}/versions/{version_id}/activate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Activate Version */
    post: operations["activate_version_api_v1_presentations__presentation_id__versions__version_id__activate_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/share-links/exchange": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Exchange Share Link */
    post: operations["exchange_share_link_api_v1_share_links_exchange_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/threads/{thread_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Patch Thread */
    patch: operations["patch_thread_api_v1_threads__thread_id__patch"];
    trace?: never;
  };
  "/api/v1/threads/{thread_id}/comments": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Add Comment */
    post: operations["add_comment_api_v1_threads__thread_id__comments_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AdminDeckPromptJobListResponse */
    AdminDeckPromptJobListResponse: {
      /** Items */
      items: components["schemas"]["AdminDeckPromptJobRead"][];
    };
    /** AdminDeckPromptJobRead */
    AdminDeckPromptJobRead: {
      /** Completion Tokens */
      completion_tokens: number | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Created By
       * Format: uuid
       */
      created_by: string;
      /** Creator Email */
      creator_email: string;
      /** Error */
      error: string | null;
      /** Finished At */
      finished_at: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Is Generation
       * @default false
       */
      is_generation: boolean;
      /** Llm Model */
      llm_model: string | null;
      /**
       * Presentation Id
       * Format: uuid
       */
      presentation_id: string;
      /** Presentation Title */
      presentation_title: string;
      /** Progress */
      progress: number;
      /** Prompt Preview */
      prompt_preview: string;
      /** Prompt Tokens */
      prompt_tokens: number | null;
      /** Result Version Id */
      result_version_id: string | null;
      /**
       * Source Version Id
       * Format: uuid
       */
      source_version_id: string;
      /** Started At */
      started_at: string | null;
      /** Status */
      status: string;
      /** Total Tokens */
      total_tokens: number | null;
    };
    /** AdminEntraSettingsPatch */
    AdminEntraSettingsPatch: {
      /**
       * Clear Entra Client Secret
       * @default false
       */
      clear_entra_client_secret: boolean;
      /** Entra Authority Host */
      entra_authority_host?: string | null;
      /** Entra Client Id */
      entra_client_id?: string | null;
      /** Entra Client Secret */
      entra_client_secret?: string | null;
      /** Entra Enabled */
      entra_enabled?: boolean | null;
      /** Entra Tenant Id */
      entra_tenant_id?: string | null;
    };
    /** AdminEntraSettingsRead */
    AdminEntraSettingsRead: {
      /** Entra Authority Host */
      entra_authority_host: string | null;
      /** Entra Client Id */
      entra_client_id: string | null;
      /** Entra Client Secret Configured */
      entra_client_secret_configured: boolean;
      /** Entra Enabled */
      entra_enabled: boolean;
      /** Entra Redirect Uri */
      entra_redirect_uri: string;
      /** Entra Tenant Id */
      entra_tenant_id: string | null;
      /** Public Api Url */
      public_api_url: string;
    };
    /** AdminExportJobListResponse */
    AdminExportJobListResponse: {
      /** Items */
      items: components["schemas"]["AdminExportJobRead"][];
    };
    /** AdminExportJobRead */
    AdminExportJobRead: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Created By
       * Format: uuid
       */
      created_by: string;
      /** Error */
      error: string | null;
      /** Finished At */
      finished_at: string | null;
      /** Format */
      format: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Presentation Id
       * Format: uuid
       */
      presentation_id: string;
      /** Presentation Title */
      presentation_title: string;
      /** Progress */
      progress: number;
      /** Status */
      status: string;
      /**
       * Version Id
       * Format: uuid
       */
      version_id: string;
    };
    /** AdminLlmSettingsPatch */
    AdminLlmSettingsPatch: {
      /**
       * Anthropic Api Base
       * @description Optional Anthropic API base; empty clears DB override.
       */
      anthropic_api_base?: string | null;
      /**
       * Anthropic Api Key
       * @description Written only on save; stored encrypted.
       */
      anthropic_api_key?: string | null;
      /**
       * Clear Anthropic Api Base
       * @default false
       */
      clear_anthropic_api_base: boolean;
      /**
       * Clear Anthropic Api Key
       * @default false
       */
      clear_anthropic_api_key: boolean;
      /**
       * Clear Litellm Api Base
       * @description Remove DB base URL; use LITELLM_API_BASE env only.
       * @default false
       */
      clear_litellm_api_base: boolean;
      /**
       * Clear Litellm Api Key
       * @default false
       */
      clear_litellm_api_key: boolean;
      /**
       * Clear Openai Api Base
       * @default false
       */
      clear_openai_api_base: boolean;
      /**
       * Clear Openai Api Key
       * @default false
       */
      clear_openai_api_key: boolean;
      /**
       * Deck Llm Provider
       * @description litellm | openai | claude
       */
      deck_llm_provider?: string | null;
      /**
       * Litellm Api Base
       * @description OpenAI-compatible API root (e.g. https://litellm.internal/v1). Empty string clears DB override.
       */
      litellm_api_base?: string | null;
      /**
       * Litellm Api Key
       * @description Written only on save; stored encrypted server-side and never echoed back.
       */
      litellm_api_key?: string | null;
      /**
       * Openai Api Base
       * @description Optional OpenAI API base; empty clears DB override.
       */
      openai_api_base?: string | null;
      /**
       * Openai Api Key
       * @description Written only on save; stored encrypted.
       */
      openai_api_key?: string | null;
    };
    /**
     * AdminLlmSettingsRead
     * @description System-wide deck LLM: LiteLLM (HTTP), OpenAI SDK, or Anthropic SDK.
     */
    AdminLlmSettingsRead: {
      /** Anthropic Api Base */
      anthropic_api_base?: string | null;
      /**
       * Anthropic Api Base Configured
       * @default false
       */
      anthropic_api_base_configured: boolean;
      /**
       * Anthropic Api Key Configured
       * @default false
       */
      anthropic_api_key_configured: boolean;
      /**
       * Deck Llm Provider
       * @description Active backend: litellm | openai | claude.
       * @default litellm
       */
      deck_llm_provider: string;
      /**
       * Litellm Api Base
       * @description Effective base URL (database override, else LITELLM_API_BASE env).
       */
      litellm_api_base?: string | null;
      /**
       * Litellm Api Base Configured
       * @description True when a non-empty base URL is set (DB or env).
       * @default false
       */
      litellm_api_base_configured: boolean;
      /**
       * Litellm Api Key Configured
       * @default false
       */
      litellm_api_key_configured: boolean;
      /**
       * Litellm Api Key Stored Encrypted
       * @description API key is never returned; stored encrypted (Fernet, same as other secrets).
       * @default true
       */
      litellm_api_key_stored_encrypted: boolean;
      /** Openai Api Base */
      openai_api_base?: string | null;
      /**
       * Openai Api Base Configured
       * @default false
       */
      openai_api_base_configured: boolean;
      /**
       * Openai Api Key Configured
       * @default false
       */
      openai_api_key_configured: boolean;
    };
    /** AdminPresentationListResponse */
    AdminPresentationListResponse: {
      /** Items */
      items: components["schemas"]["AdminPresentationRow"][];
    };
    /** AdminPresentationRow */
    AdminPresentationRow: {
      /** Current Version Id */
      current_version_id: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Owner Email */
      owner_email: string;
      /**
       * Owner Id
       * Format: uuid
       */
      owner_id: string;
      /** Title */
      title: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Version Count */
      version_count: number;
    };
    /** AdminSetupRead */
    AdminSetupRead: {
      /** Entra Client Id Configured */
      entra_client_id_configured: boolean;
      /** Entra Client Secret Configured */
      entra_client_secret_configured: boolean;
      /** Entra Enabled */
      entra_enabled: boolean;
      /** Entra Login Ready */
      entra_login_ready: boolean;
      /** Entra Redirect Uri */
      entra_redirect_uri: string;
      /** Entra Tenant Id Configured */
      entra_tenant_id_configured: boolean;
      /** Local Password Auth Enabled */
      local_password_auth_enabled: boolean;
      /** Public Api Url */
      public_api_url: string;
      /** Public App Url */
      public_app_url: string;
      /** Smtp Enabled */
      smtp_enabled: boolean;
      /** Smtp Ready */
      smtp_ready: boolean;
    };
    /** AdminSmtpSettingsPatch */
    AdminSmtpSettingsPatch: {
      /**
       * Clear Smtp Password
       * @default false
       */
      clear_smtp_password: boolean;
      /** Smtp Auth Mode */
      smtp_auth_mode?: ("login" | "none") | null;
      /** Smtp Enabled */
      smtp_enabled?: boolean | null;
      /** Smtp From */
      smtp_from?: string | null;
      /** Smtp Host */
      smtp_host?: string | null;
      /** Smtp Implicit Tls */
      smtp_implicit_tls?: boolean | null;
      /**
       * Smtp Password
       * @description Written only on save; stored encrypted server-side and never echoed back.
       */
      smtp_password?: string | null;
      /** Smtp Port */
      smtp_port?: number | null;
      /** Smtp Starttls */
      smtp_starttls?: boolean | null;
      /** Smtp Username */
      smtp_username?: string | null;
      /** Smtp Validate Certs */
      smtp_validate_certs?: boolean | null;
    };
    /** AdminSmtpSettingsRead */
    AdminSmtpSettingsRead: {
      /**
       * Smtp Auth Mode
       * @enum {string}
       */
      smtp_auth_mode: "login" | "none";
      /** Smtp Enabled */
      smtp_enabled: boolean;
      /** Smtp From */
      smtp_from?: string | null;
      /** Smtp Host */
      smtp_host?: string | null;
      /** Smtp Implicit Tls */
      smtp_implicit_tls: boolean;
      /** Smtp Password Configured */
      smtp_password_configured: boolean;
      /**
       * Smtp Password Stored Encrypted
       * @description SMTP password is never returned; at rest it is encrypted (Fernet, same key as Entra secrets).
       * @default true
       */
      smtp_password_stored_encrypted: boolean;
      /** Smtp Port */
      smtp_port: number;
      /** Smtp Ready */
      smtp_ready: boolean;
      /** Smtp Starttls */
      smtp_starttls: boolean;
      /** Smtp Username */
      smtp_username?: string | null;
      /** Smtp Validate Certs */
      smtp_validate_certs: boolean;
    };
    /**
     * AdminSmtpTestRequest
     * @description Optional override; defaults to the signed-in admin user's email.
     */
    AdminSmtpTestRequest: {
      /** To */
      to?: string | null;
    };
    /** AdminSmtpTestResponse */
    AdminSmtpTestResponse: {
      /**
       * Ok
       * @default true
       */
      ok: boolean;
      /**
       * To
       * Format: email
       */
      to: string;
    };
    /** AdminStatsRead */
    AdminStatsRead: {
      /** App Log Rows 24H */
      app_log_rows_24h: number;
      /** Audit Events 24H */
      audit_events_24h: number;
      /** Deck Prompt Jobs */
      deck_prompt_jobs: number;
      /** Deck Prompt Jobs 24H */
      deck_prompt_jobs_24h: number;
      /** Export Jobs */
      export_jobs: number;
      /** Llm Completion Tokens 24H */
      llm_completion_tokens_24h: number;
      /** Llm Prompt Tokens 24H */
      llm_prompt_tokens_24h: number;
      /** Llm Total Tokens 24H */
      llm_total_tokens_24h: number;
      /** Presentations */
      presentations: number;
      /** Users */
      users: number;
      /** Versions */
      versions: number;
    };
    /** AdminUserListResponse */
    AdminUserListResponse: {
      /** Items */
      items: components["schemas"]["AdminUserRead"][];
    };
    /** AdminUserRead */
    AdminUserRead: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Display Name */
      display_name: string | null;
      /** Email */
      email: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Last Login At */
      last_login_at: string | null;
      /** Role */
      role: string;
    };
    /** AppLogListResponse */
    AppLogListResponse: {
      /** Items */
      items: components["schemas"]["AppLogRead"][];
      /** Next Cursor */
      next_cursor?: number | null;
    };
    /**
     * AppLogRead
     * @description `app_logs.logger` is exposed as `channel` in the API.
     */
    AppLogRead: {
      /**
       * Channel
       * @description http | auth | audit | script
       */
      channel: string;
      /** Event */
      event: string | null;
      /** Id */
      id: number;
      /** Latency Ms */
      latency_ms: number | null;
      /** Level */
      level: string;
      /** Method */
      method: string;
      /** Path */
      path: string;
      /** Payload */
      payload: {
        [key: string]: unknown;
      } | null;
      /** Request Id */
      request_id: string | null;
      /** Status Code */
      status_code: number | null;
      /**
       * Ts
       * Format: date-time
       */
      ts: string;
      /** User Id */
      user_id: string | null;
    };
    /** AuditLogListResponse */
    AuditLogListResponse: {
      /** Items */
      items: components["schemas"]["AuditLogRead"][];
    };
    /** AuditLogRead */
    AuditLogRead: {
      /** Action */
      action: string;
      /** Actor Id */
      actor_id: string | null;
      /** Id */
      id: number;
      /** Ip */
      ip: string | null;
      /** Metadata */
      metadata: {
        [key: string]: unknown;
      } | null;
      /** Target Id */
      target_id: string | null;
      /** Target Kind */
      target_kind: string | null;
      /**
       * Ts
       * Format: date-time
       */
      ts: string;
    };
    /** AuthConfigResponse */
    AuthConfigResponse: {
      /** Entra Enabled */
      entra_enabled: boolean;
      /** Entra Login Url */
      entra_login_url?: string | null;
      /** Local Password Auth Enabled */
      local_password_auth_enabled: boolean;
    };
    /**
     * AuthProvider
     * @enum {string}
     */
    AuthProvider: "local" | "entra";
    /** Body_upload_html_version_api_v1_presentations__presentation_id__versions_post */
    Body_upload_html_version_api_v1_presentations__presentation_id__versions_post: {
      /** File */
      file: string;
    };
    /** CommentCreate */
    CommentCreate: {
      /** Body */
      body: string;
    };
    /** CommentRead */
    CommentRead: {
      /** Author Display Name */
      author_display_name?: string | null;
      /** Author Id */
      author_id?: string | null;
      /** Body */
      body: string;
      /** Body Format */
      body_format: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Edited At */
      edited_at: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
    };
    /** DeckPromptJobCreate */
    DeckPromptJobCreate: {
      /** Prompt */
      prompt: string;
    };
    /** DeckPromptJobRead */
    DeckPromptJobRead: {
      /** Completion Tokens */
      completion_tokens?: number | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Error */
      error: string | null;
      /** Finished At */
      finished_at: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Is Generation
       * @default false
       */
      is_generation: boolean;
      /** Llm Model */
      llm_model?: string | null;
      /**
       * Presentation Id
       * Format: uuid
       */
      presentation_id: string;
      /** Progress */
      progress: number;
      /** Prompt Tokens */
      prompt_tokens?: number | null;
      /** Result Version Id */
      result_version_id: string | null;
      /**
       * Source Version Id
       * Format: uuid
       */
      source_version_id: string;
      /** Started At */
      started_at: string | null;
      status: components["schemas"]["DeckPromptJobStatus"];
      /** Status Message */
      status_message: string | null;
      /** Total Tokens */
      total_tokens?: number | null;
    };
    /**
     * DeckPromptJobStatus
     * @enum {string}
     */
    DeckPromptJobStatus: "queued" | "running" | "succeeded" | "failed";
    /** DirectoryUserListResponse */
    DirectoryUserListResponse: {
      /** Items */
      items: components["schemas"]["DirectoryUserRead"][];
    };
    /** DirectoryUserRead */
    DirectoryUserRead: {
      /** Display Name */
      display_name?: string | null;
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Entra Object Id */
      entra_object_id: string;
      /** User Type */
      user_type?: string | null;
    };
    /** EmbedResponse */
    EmbedResponse: {
      /** Iframe Src */
      iframe_src: string;
      /** Slide Count */
      slide_count: number;
      /**
       * Version Id
       * Format: uuid
       */
      version_id: string;
    };
    /** ExportCreate */
    ExportCreate: {
      /** @default pdf */
      format: components["schemas"]["ExportFormat"];
      /** Options */
      options?: {
        [key: string]: unknown;
      };
      /** Scope */
      scope?: {
        [key: string]: unknown;
      };
      /** Version Id */
      version_id?: string | null;
    };
    /**
     * ExportFormat
     * @enum {string}
     */
    ExportFormat: "pdf" | "single_html";
    /** ExportJobRead */
    ExportJobRead: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Error */
      error: string | null;
      /** Finished At */
      finished_at: string | null;
      format: components["schemas"]["ExportFormat"];
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Output Path */
      output_path: string | null;
      /**
       * Presentation Id
       * Format: uuid
       */
      presentation_id: string;
      /** Progress */
      progress: number;
      /** Started At */
      started_at: string | null;
      status: components["schemas"]["ExportStatus"];
      /**
       * Version Id
       * Format: uuid
       */
      version_id: string;
    };
    /**
     * ExportStatus
     * @enum {string}
     */
    ExportStatus: "queued" | "running" | "succeeded" | "failed";
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** LoginRequest */
    LoginRequest: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Password */
      password: string;
    };
    /** LoginResponse */
    LoginResponse: {
      /** Access Token */
      access_token: string;
      /** Expires In */
      expires_in: number;
      /**
       * Token Type
       * @default bearer
       */
      token_type: string;
      user: components["schemas"]["UserPublic"];
    };
    /** MessageResponse */
    MessageResponse: {
      /** Message */
      message: string;
    };
    /**
     * PresentationAccess
     * @enum {string}
     */
    PresentationAccess: "admin" | "owner" | "editor" | "commenter" | "user";
    /** PresentationCreate */
    PresentationCreate: {
      /** Description */
      description?: string | null;
      /** Title */
      title: string;
    };
    /** PresentationGenerateFromPromptCreate */
    PresentationGenerateFromPromptCreate: {
      /** Description */
      description?: string | null;
      /** Prompt */
      prompt: string;
      /** Title */
      title: string;
    };
    /** PresentationGenerateFromPromptResponse */
    PresentationGenerateFromPromptResponse: {
      job: components["schemas"]["DeckPromptJobRead"];
      presentation: components["schemas"]["PresentationRead"];
    };
    /** PresentationListResponse */
    PresentationListResponse: {
      /** Items */
      items: components["schemas"]["PresentationRead"][];
    };
    /** PresentationMemberCreate */
    PresentationMemberCreate: {
      /** Display Name */
      display_name?: string | null;
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Entra Object Id */
      entra_object_id: string;
      role: components["schemas"]["PresentationMemberRole"];
      /** User Type */
      user_type?: string | null;
    };
    /** PresentationMemberListResponse */
    PresentationMemberListResponse: {
      /** Items */
      items: components["schemas"]["PresentationMemberRead"][];
    };
    /** PresentationMemberRead */
    PresentationMemberRead: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Granted By
       * Format: uuid
       */
      granted_by: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Presentation Id
       * Format: uuid
       */
      presentation_id: string;
      /** Principal Display Name */
      principal_display_name: string | null;
      /** Principal Email */
      principal_email: string;
      /** Principal Entra Object Id */
      principal_entra_object_id: string;
      /** Principal Tenant Id */
      principal_tenant_id: string;
      /** Principal User Type */
      principal_user_type: string | null;
      role: components["schemas"]["PresentationMemberRole"];
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** User Id */
      user_id: string | null;
    };
    /**
     * PresentationMemberRole
     * @enum {string}
     */
    PresentationMemberRole: "editor" | "user";
    /** PresentationMemberUpdate */
    PresentationMemberUpdate: {
      role: components["schemas"]["PresentationMemberRole"];
    };
    /** PresentationRead */
    PresentationRead: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      current_user_role?: components["schemas"]["PresentationAccess"] | null;
      current_version?: components["schemas"]["VersionRead"] | null;
      /** Current Version Id */
      current_version_id: string | null;
      /** Description */
      description: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Owner Id
       * Format: uuid
       */
      owner_id: string;
      /** Title */
      title: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** PresentationUpdate */
    PresentationUpdate: {
      /** Description */
      description?: string | null;
      /** Title */
      title?: string | null;
    };
    /** ShareLinkCreate */
    ShareLinkCreate: {
      /** Expires In Hours */
      expires_in_hours?: number | null;
      /** Note */
      note?: string | null;
      /** @default viewer */
      role: components["schemas"]["ShareRole"];
    };
    /** ShareLinkCreateResponse */
    ShareLinkCreateResponse: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Expires At */
      expires_at: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Note */
      note: string | null;
      /**
       * Presentation Id
       * Format: uuid
       */
      presentation_id: string;
      /** Revoked At */
      revoked_at: string | null;
      role: components["schemas"]["ShareRole"];
      /** Share Token */
      share_token: string;
      /** Share Url */
      share_url: string;
    };
    /** ShareLinkExchangeRequest */
    ShareLinkExchangeRequest: {
      /** Token */
      token: string;
    };
    /** ShareLinkExchangeResponse */
    ShareLinkExchangeResponse: {
      /** Access Token */
      access_token: string;
      /** Expires In */
      expires_in: number;
      /**
       * Presentation Id
       * Format: uuid
       */
      presentation_id: string;
      role: components["schemas"]["ShareRole"];
      /**
       * Token Type
       * @default bearer
       */
      token_type: string;
    };
    /** ShareLinkListResponse */
    ShareLinkListResponse: {
      /** Items */
      items: components["schemas"]["ShareLinkRead"][];
    };
    /** ShareLinkRead */
    ShareLinkRead: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Expires At */
      expires_at: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Note */
      note: string | null;
      /**
       * Presentation Id
       * Format: uuid
       */
      presentation_id: string;
      /** Revoked At */
      revoked_at: string | null;
      role: components["schemas"]["ShareRole"];
    };
    /**
     * ShareRole
     * @enum {string}
     */
    ShareRole: "viewer" | "commenter" | "editor";
    /** SlideRead */
    SlideRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Selector */
      selector: string;
      /** Slide Index */
      slide_index: number;
      /** Title */
      title: string | null;
    };
    /** ThreadCreate */
    ThreadCreate: {
      /** Anchor X */
      anchor_x: number;
      /** Anchor Y */
      anchor_y: number;
      /** First Comment */
      first_comment: string;
      /** Slide Index */
      slide_index: number;
      /**
       * Version Id
       * Format: uuid
       */
      version_id: string;
    };
    /** ThreadListResponse */
    ThreadListResponse: {
      /** Items */
      items: components["schemas"]["ThreadRead"][];
    };
    /** ThreadPatch */
    ThreadPatch: {
      status: components["schemas"]["ThreadStatus"];
    };
    /** ThreadRead */
    ThreadRead: {
      /** Anchor X */
      anchor_x: number;
      /** Anchor Y */
      anchor_y: number;
      /**
       * Comments
       * @default []
       */
      comments: components["schemas"]["CommentRead"][];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Created By */
      created_by?: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Presentation Id
       * Format: uuid
       */
      presentation_id: string;
      /** Resolved At */
      resolved_at: string | null;
      /** Slide Index */
      slide_index: number;
      status: components["schemas"]["ThreadStatus"];
      /**
       * Version Id
       * Format: uuid
       */
      version_id: string;
    };
    /**
     * ThreadStatus
     * @enum {string}
     */
    ThreadStatus: "open" | "resolved";
    /** UserPublic */
    UserPublic: {
      auth_provider: components["schemas"]["AuthProvider"];
      /** Display Name */
      display_name: string | null;
      /** Email */
      email: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      role: components["schemas"]["UserRole"];
    };
    /**
     * UserRole
     * @enum {string}
     */
    UserRole: "admin" | "user";
    /** UserSettingsRead */
    UserSettingsRead: {
      /** Anthropic Api Base */
      anthropic_api_base?: string | null;
      /**
       * Anthropic Api Key Configured
       * @default false
       */
      anthropic_api_key_configured: boolean;
      /** Litellm Api Base */
      litellm_api_base?: string | null;
      /**
       * Litellm Api Key Configured
       * @default false
       */
      litellm_api_key_configured: boolean;
      /**
       * Llm Api Key Configured
       * @description True if any per-provider or legacy API key is stored.
       * @default false
       */
      llm_api_key_configured: boolean;
      /** Llm Provider */
      llm_provider?: string | null;
      /** Openai Api Base */
      openai_api_base?: string | null;
      /**
       * Openai Api Key Configured
       * @default false
       */
      openai_api_key_configured: boolean;
    };
    /** UserSettingsUpdate */
    UserSettingsUpdate: {
      /** Anthropic Api Base */
      anthropic_api_base?: string | null;
      /** Anthropic Api Key */
      anthropic_api_key?: string | null;
      /**
       * Clear Anthropic Api Base
       * @default false
       */
      clear_anthropic_api_base: boolean;
      /**
       * Clear Anthropic Api Key
       * @default false
       */
      clear_anthropic_api_key: boolean;
      /**
       * Clear Litellm Api Base
       * @default false
       */
      clear_litellm_api_base: boolean;
      /**
       * Clear Litellm Api Key
       * @default false
       */
      clear_litellm_api_key: boolean;
      /**
       * Clear Llm Api Key
       * @default false
       */
      clear_llm_api_key: boolean;
      /**
       * Clear Llm Provider
       * @description When true, clear personal provider override (use organization defaults only).
       * @default false
       */
      clear_llm_provider: boolean;
      /**
       * Clear Openai Api Base
       * @default false
       */
      clear_openai_api_base: boolean;
      /**
       * Clear Openai Api Key
       * @default false
       */
      clear_openai_api_key: boolean;
      /** Litellm Api Base */
      litellm_api_base?: string | null;
      /** Litellm Api Key */
      litellm_api_key?: string | null;
      /**
       * Llm Api Key
       * @description Deprecated: use openai_api_key / anthropic_api_key / litellm_api_key.
       */
      llm_api_key?: string | null;
      /**
       * Llm Provider
       * @description openai | claude | litellm (omit to leave unchanged).
       */
      llm_provider?: string | null;
      /** Openai Api Base */
      openai_api_base?: string | null;
      /** Openai Api Key */
      openai_api_key?: string | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /** VersionRead */
    VersionRead: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Entry Path */
      entry_path: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Origin */
      origin: string;
      /**
       * Presentation Id
       * Format: uuid
       */
      presentation_id: string;
      /** Sha256 */
      sha256: string;
      /** Size Bytes */
      size_bytes: number;
      /**
       * Slides
       * @default []
       */
      slides: components["schemas"]["SlideRead"][];
      /** Storage Kind */
      storage_kind: string;
      /** Version Number */
      version_number: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  serve_asset_a__version_id___file_path__get: {
    parameters: {
      query: {
        /** @description Unix expiry time */
        exp: number;
        sig: string;
        /** @description User id */
        sub: string;
        role: string;
      };
      header?: never;
      path: {
        version_id: string;
        file_path: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_audit_api_v1_admin_audit_get: {
    parameters: {
      query?: {
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuditLogListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_deck_prompt_jobs_admin_api_v1_admin_deck_prompt_jobs_get: {
    parameters: {
      query?: {
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdminDeckPromptJobListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_export_jobs_admin_api_v1_admin_jobs_get: {
    parameters: {
      query?: {
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdminExportJobListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_logs_api_v1_admin_logs_get: {
    parameters: {
      query?: {
        limit?: number;
        level?: string | null;
        /** @description Filter by channel (http, auth, audit, script) */
        channel?: string | null;
        request_id?: string | null;
        user_id?: string | null;
        since?: string | null;
        /** @description Only rows whose path starts with this prefix (e.g. /api/v1/admin) */
        path_prefix?: string | null;
        /** @description Substring match on `event` (e.g. auth.login, http.request) */
        event_contains?: string | null;
        /** @description Use `id` of oldest row from prior page */
        cursor?: number | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AppLogListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_presentations_admin_api_v1_admin_presentations_get: {
    parameters: {
      query?: {
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdminPresentationListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  admin_entra_settings_get_api_v1_admin_settings_entra_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdminEntraSettingsRead"];
        };
      };
    };
  };
  admin_entra_settings_patch_api_v1_admin_settings_entra_patch: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AdminEntraSettingsPatch"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdminEntraSettingsRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  admin_llm_settings_get_api_v1_admin_settings_llm_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdminLlmSettingsRead"];
        };
      };
    };
  };
  admin_llm_settings_patch_api_v1_admin_settings_llm_patch: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AdminLlmSettingsPatch"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdminLlmSettingsRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  admin_smtp_settings_get_api_v1_admin_settings_smtp_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdminSmtpSettingsRead"];
        };
      };
    };
  };
  admin_smtp_settings_patch_api_v1_admin_settings_smtp_patch: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AdminSmtpSettingsPatch"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdminSmtpSettingsRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  admin_smtp_test_api_v1_admin_settings_smtp_test_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["AdminSmtpTestRequest"] | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdminSmtpTestResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  admin_setup_api_v1_admin_setup_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdminSetupRead"];
        };
      };
    };
  };
  admin_stats_api_v1_admin_stats_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdminStatsRead"];
        };
      };
    };
  };
  list_users_api_v1_admin_users_get: {
    parameters: {
      query?: {
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdminUserListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  auth_config_api_v1_auth_config_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthConfigResponse"];
        };
      };
    };
  };
  entra_callback_api_v1_auth_entra_callback_get: {
    parameters: {
      query?: {
        code?: string | null;
        state?: string | null;
        error?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  entra_login_api_v1_auth_entra_login_get: {
    parameters: {
      query?: {
        next?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  login_api_v1_auth_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LoginResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  logout_api_v1_auth_logout_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MessageResponse"];
        };
      };
    };
  };
  me_api_v1_auth_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserPublic"];
        };
      };
    };
  };
  me_settings_api_v1_auth_me_settings_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserSettingsRead"];
        };
      };
    };
  };
  me_settings_patch_api_v1_auth_me_settings_patch: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserSettingsUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserSettingsRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  refresh_api_v1_auth_refresh_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LoginResponse"];
        };
      };
    };
  };
  delete_comment_api_v1_comments__comment_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        comment_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_deck_prompt_job_api_v1_deck_prompt_jobs__job_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DeckPromptJobRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  directory_users_api_v1_directory_users_get: {
    parameters: {
      query: {
        q: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DirectoryUserListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_export_job_api_v1_exports__job_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ExportJobRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  download_export_file_api_v1_exports__job_id__file_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_presentations_api_v1_presentations_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PresentationListResponse"];
        };
      };
    };
  };
  create_presentation_api_v1_presentations_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PresentationCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PresentationRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  generate_presentation_from_prompt_api_v1_presentations_generate_from_prompt_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PresentationGenerateFromPromptCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PresentationGenerateFromPromptResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_presentation_detail_api_v1_presentations__presentation_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        presentation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PresentationRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_presentation_api_v1_presentations__presentation_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        presentation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_presentation_api_v1_presentations__presentation_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        presentation_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PresentationUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PresentationRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_deck_prompt_job_api_v1_presentations__presentation_id__deck_prompt_jobs_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        presentation_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DeckPromptJobCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DeckPromptJobRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  embed_iframe_api_v1_presentations__presentation_id__embed_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        presentation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EmbedResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_export_job_api_v1_presentations__presentation_id__exports_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        presentation_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ExportCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ExportJobRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_presentation_members_api_v1_presentations__presentation_id__members_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        presentation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PresentationMemberListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_presentation_member_api_v1_presentations__presentation_id__members_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        presentation_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PresentationMemberCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PresentationMemberRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_presentation_member_api_v1_presentations__presentation_id__members__member_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        member_id: string;
        presentation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_presentation_member_api_v1_presentations__presentation_id__members__member_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        member_id: string;
        presentation_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PresentationMemberUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PresentationMemberRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_share_links_api_v1_presentations__presentation_id__share_links_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        presentation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ShareLinkListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_share_link_api_v1_presentations__presentation_id__share_links_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        presentation_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ShareLinkCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ShareLinkCreateResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  revoke_share_link_api_v1_presentations__presentation_id__share_links__share_link_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        share_link_id: string;
        presentation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_threads_api_v1_presentations__presentation_id__threads_get: {
    parameters: {
      query?: {
        /** @description Filter by version */
        version_id?: string | null;
      };
      header?: never;
      path: {
        presentation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ThreadListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_thread_api_v1_presentations__presentation_id__threads_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        presentation_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ThreadCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ThreadRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_versions_api_v1_presentations__presentation_id__versions_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        presentation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["VersionRead"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  upload_html_version_api_v1_presentations__presentation_id__versions_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        presentation_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_upload_html_version_api_v1_presentations__presentation_id__versions_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["VersionRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  activate_version_api_v1_presentations__presentation_id__versions__version_id__activate_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        version_id: string;
        presentation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["VersionRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  exchange_share_link_api_v1_share_links_exchange_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ShareLinkExchangeRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ShareLinkExchangeResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  patch_thread_api_v1_threads__thread_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        thread_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ThreadPatch"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ThreadRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  add_comment_api_v1_threads__thread_id__comments_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        thread_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CommentCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CommentRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
}
