/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/a/{version_id}/{file_path}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Serve Asset */
    get: operations["serve_asset_a__version_id___file_path__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/logs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Logs */
    get: operations["list_logs_api_v1_admin_logs_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login */
    post: operations["login_api_v1_auth_login_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Logout */
    post: operations["logout_api_v1_auth_logout_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Me */
    get: operations["me_api_v1_auth_me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Refresh */
    post: operations["refresh_api_v1_auth_refresh_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/comments/{comment_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete Comment */
    delete: operations["delete_comment_api_v1_comments__comment_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/exports/{job_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Export Job */
    get: operations["get_export_job_api_v1_exports__job_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/presentations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Presentations */
    get: operations["list_presentations_api_v1_presentations_get"];
    put?: never;
    /** Create Presentation */
    post: operations["create_presentation_api_v1_presentations_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/presentations/{presentation_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Presentation Detail */
    get: operations["get_presentation_detail_api_v1_presentations__presentation_id__get"];
    put?: never;
    post?: never;
    /** Delete Presentation */
    delete: operations["delete_presentation_api_v1_presentations__presentation_id__delete"];
    options?: never;
    head?: never;
    /** Update Presentation */
    patch: operations["update_presentation_api_v1_presentations__presentation_id__patch"];
    trace?: never;
  };
  "/api/v1/presentations/{presentation_id}/embed": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Embed Iframe */
    get: operations["embed_iframe_api_v1_presentations__presentation_id__embed_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/presentations/{presentation_id}/exports": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Export Job */
    post: operations["create_export_job_api_v1_presentations__presentation_id__exports_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/presentations/{presentation_id}/shares": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Share Links */
    get: operations["list_share_links_api_v1_presentations__presentation_id__shares_get"];
    put?: never;
    /** Create Share Link */
    post: operations["create_share_link_api_v1_presentations__presentation_id__shares_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/presentations/{presentation_id}/shares/{share_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Revoke Share Link */
    delete: operations["revoke_share_link_api_v1_presentations__presentation_id__shares__share_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/presentations/{presentation_id}/threads": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Threads */
    get: operations["list_threads_api_v1_presentations__presentation_id__threads_get"];
    put?: never;
    /** Create Thread */
    post: operations["create_thread_api_v1_presentations__presentation_id__threads_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/presentations/{presentation_id}/versions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Versions */
    get: operations["list_versions_api_v1_presentations__presentation_id__versions_get"];
    put?: never;
    /** Upload Html Version */
    post: operations["upload_html_version_api_v1_presentations__presentation_id__versions_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/presentations/{presentation_id}/versions/{version_id}/activate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Activate Version */
    post: operations["activate_version_api_v1_presentations__presentation_id__versions__version_id__activate_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/shares/exchange": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Exchange Share Token */
    post: operations["exchange_share_token_api_v1_shares_exchange_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/threads/{thread_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Patch Thread */
    patch: operations["patch_thread_api_v1_threads__thread_id__patch"];
    trace?: never;
  };
  "/api/v1/threads/{thread_id}/comments": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Add Comment */
    post: operations["add_comment_api_v1_threads__thread_id__comments_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AppLogListResponse */
    AppLogListResponse: {
      /** Items */
      items: components["schemas"]["AppLogRead"][];
      /** Next Cursor */
      next_cursor?: number | null;
    };
    /**
     * AppLogRead
     * @description `app_logs.logger` is exposed as `channel` in the API.
     */
    AppLogRead: {
      /**
       * Channel
       * @description http | auth | audit | script
       */
      channel: string;
      /** Event */
      event: string | null;
      /** Id */
      id: number;
      /** Latency Ms */
      latency_ms: number | null;
      /** Level */
      level: string;
      /** Method */
      method: string;
      /** Path */
      path: string;
      /** Payload */
      payload: {
        [key: string]: unknown;
      } | null;
      /** Request Id */
      request_id: string | null;
      /** Status Code */
      status_code: number | null;
      /**
       * Ts
       * Format: date-time
       */
      ts: string;
      /** User Id */
      user_id: string | null;
    };
    /** Body_upload_html_version_api_v1_presentations__presentation_id__versions_post */
    Body_upload_html_version_api_v1_presentations__presentation_id__versions_post: {
      /** File */
      file: string;
    };
    /** CommentCreate */
    CommentCreate: {
      /** Body */
      body: string;
    };
    /** CommentRead */
    CommentRead: {
      /** Author Display Name */
      author_display_name?: string | null;
      /** Author Id */
      author_id?: string | null;
      /** Body */
      body: string;
      /** Body Format */
      body_format: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Edited At */
      edited_at: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
    };
    /** EmbedResponse */
    EmbedResponse: {
      /** Iframe Src */
      iframe_src: string;
      /** Slide Count */
      slide_count: number;
      /**
       * Version Id
       * Format: uuid
       */
      version_id: string;
    };
    /** ExportCreate */
    ExportCreate: {
      /** @default pdf */
      format: components["schemas"]["ExportFormat"];
      /** Options */
      options?: {
        [key: string]: unknown;
      };
      /** Scope */
      scope?: {
        [key: string]: unknown;
      };
      /** Version Id */
      version_id?: string | null;
    };
    /**
     * ExportFormat
     * @enum {string}
     */
    ExportFormat: "pdf" | "single_html";
    /** ExportJobRead */
    ExportJobRead: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Error */
      error: string | null;
      /** Finished At */
      finished_at: string | null;
      format: components["schemas"]["ExportFormat"];
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Output Path */
      output_path: string | null;
      /**
       * Presentation Id
       * Format: uuid
       */
      presentation_id: string;
      /** Progress */
      progress: number;
      /** Started At */
      started_at: string | null;
      status: components["schemas"]["ExportStatus"];
      /**
       * Version Id
       * Format: uuid
       */
      version_id: string;
    };
    /**
     * ExportStatus
     * @enum {string}
     */
    ExportStatus: "queued" | "running" | "succeeded" | "failed";
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** LoginRequest */
    LoginRequest: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Password */
      password: string;
    };
    /** LoginResponse */
    LoginResponse: {
      /** Access Token */
      access_token: string;
      /** Expires In */
      expires_in: number;
      /**
       * Token Type
       * @default bearer
       */
      token_type: string;
      user: components["schemas"]["UserPublic"];
    };
    /** MessageResponse */
    MessageResponse: {
      /** Message */
      message: string;
    };
    /** PresentationCreate */
    PresentationCreate: {
      /** Description */
      description?: string | null;
      /** Title */
      title: string;
    };
    /** PresentationListResponse */
    PresentationListResponse: {
      /** Items */
      items: components["schemas"]["PresentationRead"][];
    };
    /** PresentationRead */
    PresentationRead: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      current_version?: components["schemas"]["VersionRead"] | null;
      /** Current Version Id */
      current_version_id: string | null;
      /** Description */
      description: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Owner Id
       * Format: uuid
       */
      owner_id: string;
      /** Title */
      title: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** PresentationUpdate */
    PresentationUpdate: {
      /** Description */
      description?: string | null;
      /** Title */
      title?: string | null;
    };
    /** ShareCreate */
    ShareCreate: {
      /** Expires At */
      expires_at?: string | null;
      /** Note */
      note?: string | null;
      /** @default viewer */
      role: components["schemas"]["ShareRole"];
    };
    /**
     * ShareCreated
     * @description Returned once when creating a link; includes the secret token.
     */
    ShareCreated: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Expires At */
      expires_at: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Note */
      note: string | null;
      /**
       * Presentation Id
       * Format: uuid
       */
      presentation_id: string;
      /** Revoked At */
      revoked_at: string | null;
      role: components["schemas"]["ShareRole"];
      /** Token */
      token: string;
    };
    /** ShareExchangeRequest */
    ShareExchangeRequest: {
      /** Token */
      token: string;
    };
    /** ShareExchangeResponse */
    ShareExchangeResponse: {
      /** Access Token */
      access_token: string;
      /** Expires In */
      expires_in: number;
      /**
       * Presentation Id
       * Format: uuid
       */
      presentation_id: string;
      role: components["schemas"]["ShareRole"];
      /**
       * Token Type
       * @default bearer
       */
      token_type: string;
    };
    /** ShareListResponse */
    ShareListResponse: {
      /** Items */
      items: components["schemas"]["ShareRead"][];
    };
    /** ShareRead */
    ShareRead: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Expires At */
      expires_at: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Note */
      note: string | null;
      /**
       * Presentation Id
       * Format: uuid
       */
      presentation_id: string;
      /** Revoked At */
      revoked_at: string | null;
      role: components["schemas"]["ShareRole"];
    };
    /**
     * ShareRole
     * @enum {string}
     */
    ShareRole: "viewer" | "commenter" | "editor";
    /** SlideRead */
    SlideRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Selector */
      selector: string;
      /** Slide Index */
      slide_index: number;
      /** Title */
      title: string | null;
    };
    /** ThreadCreate */
    ThreadCreate: {
      /** Anchor X */
      anchor_x: number;
      /** Anchor Y */
      anchor_y: number;
      /** First Comment */
      first_comment: string;
      /** Slide Index */
      slide_index: number;
      /**
       * Version Id
       * Format: uuid
       */
      version_id: string;
    };
    /** ThreadListResponse */
    ThreadListResponse: {
      /** Items */
      items: components["schemas"]["ThreadRead"][];
    };
    /** ThreadPatch */
    ThreadPatch: {
      status: components["schemas"]["ThreadStatus"];
    };
    /** ThreadRead */
    ThreadRead: {
      /** Anchor X */
      anchor_x: number;
      /** Anchor Y */
      anchor_y: number;
      /**
       * Comments
       * @default []
       */
      comments: components["schemas"]["CommentRead"][];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Created By */
      created_by?: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Presentation Id
       * Format: uuid
       */
      presentation_id: string;
      /** Resolved At */
      resolved_at: string | null;
      /** Slide Index */
      slide_index: number;
      status: components["schemas"]["ThreadStatus"];
      /**
       * Version Id
       * Format: uuid
       */
      version_id: string;
    };
    /**
     * ThreadStatus
     * @enum {string}
     */
    ThreadStatus: "open" | "resolved";
    /** UserPublic */
    UserPublic: {
      /** Display Name */
      display_name: string | null;
      /** Email */
      email: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      role: components["schemas"]["UserRole"];
    };
    /**
     * UserRole
     * @enum {string}
     */
    UserRole: "admin" | "editor" | "commenter" | "viewer";
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /** VersionRead */
    VersionRead: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Entry Path */
      entry_path: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Origin */
      origin: string;
      /**
       * Presentation Id
       * Format: uuid
       */
      presentation_id: string;
      /** Sha256 */
      sha256: string;
      /** Size Bytes */
      size_bytes: number;
      /**
       * Slides
       * @default []
       */
      slides: components["schemas"]["SlideRead"][];
      /** Storage Kind */
      storage_kind: string;
      /** Version Number */
      version_number: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  serve_asset_a__version_id___file_path__get: {
    parameters: {
      query: {
        /** @description Unix expiry time */
        exp: number;
        sig: string;
        /** @description User id */
        sub: string;
        role: string;
      };
      header?: never;
      path: {
        version_id: string;
        file_path: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_logs_api_v1_admin_logs_get: {
    parameters: {
      query?: {
        limit?: number;
        level?: string | null;
        /** @description Filter by channel (http, auth, audit, script) */
        channel?: string | null;
        request_id?: string | null;
        user_id?: string | null;
        since?: string | null;
        /** @description Use `id` of oldest row from prior page */
        cursor?: number | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AppLogListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  login_api_v1_auth_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LoginResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  logout_api_v1_auth_logout_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MessageResponse"];
        };
      };
    };
  };
  me_api_v1_auth_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserPublic"];
        };
      };
    };
  };
  refresh_api_v1_auth_refresh_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LoginResponse"];
        };
      };
    };
  };
  delete_comment_api_v1_comments__comment_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        comment_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_export_job_api_v1_exports__job_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ExportJobRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_presentations_api_v1_presentations_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PresentationListResponse"];
        };
      };
    };
  };
  create_presentation_api_v1_presentations_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PresentationCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PresentationRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_presentation_detail_api_v1_presentations__presentation_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        presentation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PresentationRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_presentation_api_v1_presentations__presentation_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        presentation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_presentation_api_v1_presentations__presentation_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        presentation_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PresentationUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PresentationRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  embed_iframe_api_v1_presentations__presentation_id__embed_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        presentation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EmbedResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_export_job_api_v1_presentations__presentation_id__exports_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        presentation_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ExportCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ExportJobRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_share_links_api_v1_presentations__presentation_id__shares_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        presentation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ShareListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_share_link_api_v1_presentations__presentation_id__shares_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        presentation_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ShareCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ShareCreated"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  revoke_share_link_api_v1_presentations__presentation_id__shares__share_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        share_id: string;
        presentation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_threads_api_v1_presentations__presentation_id__threads_get: {
    parameters: {
      query?: {
        /** @description Filter by version */
        version_id?: string | null;
      };
      header?: never;
      path: {
        presentation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ThreadListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_thread_api_v1_presentations__presentation_id__threads_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        presentation_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ThreadCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ThreadRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_versions_api_v1_presentations__presentation_id__versions_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        presentation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["VersionRead"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  upload_html_version_api_v1_presentations__presentation_id__versions_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        presentation_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_upload_html_version_api_v1_presentations__presentation_id__versions_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["VersionRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  activate_version_api_v1_presentations__presentation_id__versions__version_id__activate_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        version_id: string;
        presentation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["VersionRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  exchange_share_token_api_v1_shares_exchange_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ShareExchangeRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ShareExchangeResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  patch_thread_api_v1_threads__thread_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        thread_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ThreadPatch"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ThreadRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  add_comment_api_v1_threads__thread_id__comments_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        thread_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CommentCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CommentRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
}
